---
- name: Configure CentOS
  hosts: all
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - name: Download RPM-GPG-KEY-redhat-release
      command: "curl -o /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release https://www.redhat.com/security/data/fd431d51.txt"

    - name: Download client-tools.repo file
      command: >
        curl -o /etc/yum.repos.d/client-tools.repo
        https://ftp.redhat.com/redhat/client-tools/client-tools-for-rhel-7-server.repo
        https://ftp.redhat.com/redhat/client-tools/client-tools-for-rhel-7-server.repo

    - name: Install required packages
      yum:
        name:
          - subscription-manager
          - subscription-manager-rhsm-certificates
          - rhc
          - rhc-worker-script
          - insights-client
        state: present

    - name: Connect to Red Hat Insights
      command: "rhc connect --activation-key {{ activation_key }} --organization {{ organization_id }}"
